# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd0c513e26973bf6e03b238176ca83a35fe20988d38c7783f43a7e5c4a6b65f1f0a994e0248a557850b5067a6e1e95a2c2a8264d36f78f4387f80745c4fe46a

test:
  secret_key_base: 348a358d6a0817306569a565a9b4c9c97ba8615d295bd5aeb2e63fc678362046e86791debfbdf9f836f64861f25e427b3e66dfb7148e3f11833463b16cf4058f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
